In [1]:
import ee

import model
from pixelPairs import pixelPairs
from reader import parseKML
import numpy as np

%load_ext autoreload
%autoreload 2

In [9]:
ee.Initialize()
sar = None
ndvi = np.array([])

def unison_shuffled_copies(a, b):
    assert len(a) == len(b)
    p = np.random.permutation(len(a))
    return a[p], b[p]

In [ ]:
for array in parseKML("2018_polygons.kml"):
    X, y = pixelPairs(array, "2018-05-01", "2018-09-30")
    if len(X):
        sar = np.concatenate((sar, X), axis=0) if not sar is None else X
        ndvi = np.append(ndvi, y)

{23: [0], 24: [0], 25: [0], 26: [0], 27: [1], 28: [1], 29: [2], 30: [2], 31: [2], 32: [2], 35: [3], 6: [4], 7: [4], 16: [5], 17: [5], 36: [6], 37: [6], 38: [6], 39: [7], 40: [7], 41: [7], 42: [7], 43: [8], 44: [8], 51: [9], 52: [9], 61: [10], 62: [10], 63: [10], 64: [10]}
{23: [0], 24: [0], 25: [0], 26: [0], 27: [1], 28: [1], 29: [2], 30: [2], 31: [2], 32: [2], 35: [3], 6: [4], 7: [4], 16: [5], 17: [5], 36: [6], 37: [6], 38: [6], 39: [7], 40: [7], 41: [7], 42: [7], 43: [8], 44: [8], 51: [9], 52: [9], 61: [10], 62: [10], 63: [10], 64: [10]}
{10: [0], 11: [0], 12: [1], 13: [1], 6: [2], 7: [2], 14: [3], 15: [3], 16: [4], 17: [4], 18: [5], 19: [5], 26: [6], 27: [6]}
{16: [0], 17: [0], 18: [0], 19: [1], 20: [2], 21: [2], 22: [2], 4: [3], 11: [4], 12: [4], 24: [5], 25: [5], 26: [5], 27: [6], 28: [6], 29: [6], 30: [7], 31: [7], 36: [8], 43: [9], 44: [9], 45: [9]}


In [54]:
np.save("pixel_data/2018_avg_sar", sar)
np.save("pixel_data/2018_avg_ndvi", ndvi)

In [4]:
sar = np.load("pixel_data/2017_avg_sar.npy")
ndvi = np.load("pixel_data/2017_avg_ndvi.npy")

In [4]:
sar2017 = np.load("pixel_data/2017_sar_px.npy")
ndvi2017 = np.load("pixel_data/2017_ndvi_px.npy")
sar2018 = np.load("pixel_data/2018_sar_px.npy")
ndvi2018 = np.load("pixel_data/2018_ndvi_px.npy")
sar2019 = np.load("pixel_data/2019_sar_px.npy")
ndvi2019 = np.load("pixel_data/2019_ndvi_px.npy")

In [23]:
sar2017, ndvi2017 = unison_shuffled_copies(sar2017, ndvi2017)
sar2018, ndvi2018 = unison_shuffled_copies(sar2018, ndvi2018)
sar2019, ndvi2019 = unison_shuffled_copies(sar2019, ndvi2019)

In [26]:
sar = np.concatenate((np.take(sar2017, np.arange(400000), axis=0), np.take(sar2018, np.arange(400000), axis=0), np.take(sar2019, np.arange(400000), axis=0)), axis=0)

In [29]:
ndvi = np.concatenate((np.take(ndvi2017, np.arange(400000), axis=0), np.take(ndvi2018, np.arange(400000), axis=0), np.take(ndvi2019, np.arange(400000), axis=0)), axis=0)

In [5]:
model.train_and_test(sar, ndvi, test_split=0.15, file_name="model_2017_avg")

Training new model...
Train set size: 406
Test set size: 72
Saving to model_2017_avg...
Done!
Scoring...
Regression score: R^2=0.791316372701577


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [3]:
from joblib import dump, load
from visualize import visualize
regr = load("model_2017_avg")

In [7]:
for field_no in range(90, 93):
        visualize(field_no, regr)

Number of images:  100
[[-24.75462055 -14.21504849]]
[[-26.19781392 -16.05359619]]
[[-25.9149066  -14.43421105]]
[[-25.04104264 -15.83636753]]
[[-23.48918389 -12.92153375]]
[[-20.77470704 -12.2010376 ]]
[[-17.9631349   -8.97902065]]
[[-19.52755856 -11.15890122]]
[[-17.07825582 -10.13123766]]
[[-17.48583357 -10.04454984]]
[[-15.94967351  -9.2455378 ]]
[[-16.72501967  -8.95652209]]
[[-15.00938245  -7.98575358]]
[[-14.40122379  -7.65349838]]
[[-15.38837253  -8.95009184]]
[[-15.15322735  -9.07401718]]
[[-14.46859038  -8.79591506]]
[[-15.02750647  -7.36677447]]
[[-14.33402451  -8.86531917]]
[[-14.71108919  -7.4755374 ]]
[[-14.45331205  -7.95311105]]
[[-15.14688718  -8.62016267]]
[[-15.12213965  -8.66958225]]
[[-14.54121588  -9.47890305]]
[[-13.75396979  -8.05843034]]
[[-14.83051641  -7.98233869]]
[[-14.7422978  -9.0548276]]
[[-14.37959357  -8.81146646]]
[[-14.00915866  -7.57408675]]
[[-14.87662761  -8.00931019]]
[[-14.56066484  -8.97495649]]
[[-14.84912265  -8.89825501]]
[[-13.84880746  -8.

<Figure size 432x288 with 0 Axes>

In [16]:
import datetime
datetime.datetime.now()

datetime.datetime(2020, 2, 25, 20, 23, 5, 884591)